Safer error-handling mechanism (#379)
* Safer error-handling mechanism

Hi, this is my first time writing Rust, please go easy on me 🙂 Could you make sure I did it correct? I won't be offended if it's not any good.
This error was I think similar to the one found in https://github.com/jpochyla/psst/pull/374

The error was as follows and it would cause the app to crash and shutdown:

> thread 'main' panicked at 'called Result::unwrap() on an Err value: "SendError(..)"', psst-gui/src/controller/playback.rs:219:51

* Update playback.rs

* Update playback.rs